### ISSUE TITLE
Custom Class permissions

### ISSUE THREAD

**Issue by cesarsaenz** [catalyzeio/HipaaGram#1]
In the blog entry you mention that Contacts should have the read/create permission and that Conversation and Message should have only create permissions but in this readme you have Conversation class as having read/create. Just wanted to confirm the correct permissions.

**Comment by jault3** [comment]
@cesarsaenz the blog post is correct. You only need to set `['create']` permissions on the Conversation class. That way you can only retrieve the conversations you created, or have been invited to. Thanks for pointing this out, I'll update the README
